package com.sfyvctwaqbjhki.uwmpqfh.blfwuhtozemk;

/* loaded from: classes.dex */
public class ConstantUtil {
    public static int ACCOUNTTYPE_EMAIL = 1;
    public static int ACCOUNTTYPE_FACEBOOK = 2;
    public static int ACCOUNTTYPE_GAMECENT = 3;
    public static int ACCOUNTTYPE_GOOGLE = 4;
    public static int ACCOUNTTYPE_KAKAO = 11;
    public static int ACCOUNTTYPE_LINE = 5;
    public static int ACCOUNTTYPE_NORMAL = 0;
    public static int ACCOUNTTYPE_PHONE = 8;
    public static int ACCOUNTTYPE_VK = 6;
    public static final String ACCOUNT_PREFERENCES = "cheerlife";
    public static final int ADV_88BOX = 20;
    public static final int ADV_ADFLEX = 14;
    public static final int ADV_GOOGLE = 1;
    public static final int ADV_GW = 2;
    public static final int ADV_MOBVISTA = 17;
    public static final String BOOL_FALSE = "bool_false";
    public static final String BOOL_TRUE = "bool_true";
    public static final String BROAD_ACTION = "COM.POCKET.FUNCTION";
    public static final int BROAD_LINK = 3;
    public static final int BROAD_LOGIN = 0;
    public static final int BROAD_PARISE = 1;
    public static final int BROAD_SHARE = 2;
    public static final String COUNTRY_MOBILE_OPERATORS = "452";
    public static final String LAST_REFRESH_PAYWAY_TIME = "last_refrsh_pay";
    public static final String NEWEST_PAY_LIST_JSON = "newest_pay_list";
    public static final int ORDER_CHANNEL_CARD = 2;
    public static final int ORDER_CHANNEL_OFFICE = 1;
    public static final int ORDER_CHANNEL_WALLET = 3;
    public static final int PAYACTIVITY_GOODSLIST_POSITION = -1000;
    public static final int REQUEST_CARD_PAY = 2;
    public static final int REQUEST_COST_PLATFORM = 1;
    public static final int REQUEST_THIRD_PAY = 0;
    public static int SEND_TYPE_EMAIL = 1;
    public static int SEND_TYPE_PHONE = 0;
    public static final String SHOW_METHOD_CONFIRM_AND_PIN = "11";
    public static final String SHOW_METHOD_CONFIRM_AND_SERIAL_PIN = "10";
    public static final String SHOW_METHOD_CONFIRM_AND_WEB = "9";
    public static final String SHOW_METHOD_CONFIRM_NO_EXCHANGE = "7";
    public static final String SHOW_METHOD_CONFIRM_SYS_BROWSER = "13";
    public static final String SHOW_METHOD_CONTENT = "6";
    public static final String SHOW_METHOD_LANUCH_CONFIRM = "5";
    public static final String SHOW_METHOD_LANUCH_NO_CONFIRM = "3";
    public static final String SHOW_METHOD_PIN = "2";
    public static final String SHOW_METHOD_SERIAL_PIN = "1";
    public static final String SHOW_METHOD_SQUARED = "4";
    public static final String SHOW_METHOD_SYS_BROWSER = "12";
    public static final String SHOW_METHOD_WEB = "0";
    public static int SOURCE_ANDROID = 1;
    public static int SOURCE_IOS = 0;
    public static int SOURCE_WEB = 2;
    public static final int TOOLBAR_CUS = 2;
    public static final int TOOLBAR_LIVE = 4;
    public static final int TOOLBAR_OTHER = 3;
    public static final int TOOLBAR_PERSON = 1;
    public static final int TOOLBAR_REDSPOTS_NOT_SHOW = 0;
    public static final int TOOLBAR_REDSPOTS_SHOW = 1;
    public static final int USER_FIRST_LOGIN = 1;
    public static final int USER_NOT_FIRST_LOGIN = 0;
    public static int USER_TYPE_POSITIVE = 1;
    public static int USER_TYPE_VISTOR;
}
